/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import br.unipar.flashcar.model.Cor;
import br.unipar.flashcar.service.CorService;
import java.sql.SQLException;
import java.sql.SQLOutput;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;

/**
 *
 * @author tailon.prado
 */
public class ConsultaCor extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaCor
     */
    public ConsultaCor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idCor = new javax.swing.JTextField();
        descricaoCor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        consultaCor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCor = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        idCor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idCorKeyReleased(evt);
            }
        });

        jLabel1.setText("Id");

        jLabel2.setText("Descrição");

        consultaCor.setText("Consultar");
        consultaCor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultaCorMouseClicked(evt);
            }
        });
        consultaCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaCorActionPerformed(evt);
            }
        });

        tableCor = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tableCor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "id", "descricao"
            }
        ));
        tableCor.setFocusable(false);
        tableCor.getTableHeader().setResizingAllowed(false);
        tableCor.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableCor);
        TableColumn colIdCor = tableCor.getColumnModel().getColumn(0);
        TableColumn colDescricaoCor = tableCor.getColumnModel().getColumn(1);

        colIdCor.setPreferredWidth(50);
        colDescricaoCor.setPreferredWidth(500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultaCor, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(idCor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(descricaoCor, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descricaoCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consultaCor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultaCorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaCorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaCorMouseClicked

    private void idCorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idCorKeyReleased
        idCor.setText(idCor.getText().replaceAll("[^0-9]+", ""));
    }//GEN-LAST:event_idCorKeyReleased

    private void consultaCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaCorActionPerformed
        System.out.println("Teste");
        ArrayList<Cor> cores = new ArrayList<>();
        CorService corService = new CorService();
        
        try {
            cores = corService.findByRel(montaWhere());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao realizar a consulta. Erro: "+ ex.getMessage());
        }
        
        Object[][] obj = new Object[cores.size()][2];
        
        int linha = 0;
        for (Cor cor : cores) {
            obj[linha][0] = cor.getId();
            obj[linha][1] = cor.getDescricao();
            linha++;
        }
        
        tableCor.setModel(new javax.swing.table.DefaultTableModel(
            obj,
            new String [] {
                "id", "descricao"
            }
        ));
        TableColumn colIdCor = tableCor.getColumnModel().getColumn(0);
        TableColumn colDescricaoCor = tableCor.getColumnModel().getColumn(1);

        colIdCor.setPreferredWidth(50);
        colDescricaoCor.setPreferredWidth(500);
    }//GEN-LAST:event_consultaCorActionPerformed
    private String montaWhere(){
            String retorno = " where 1 = 1 ";
            if(!(idCor.getText().equals(""))){
                retorno += " and id = " + idCor.getText();
            }
            if(!(descricaoCor.getText().equals(""))){
                retorno += " and upper(descricao) like '%" + descricaoCor.getText().toUpperCase() +"%'";
            }
            retorno += " order by descricao asc ";
            return retorno;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaCor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaCor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaCor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaCor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaCor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultaCor;
    private javax.swing.JTextField descricaoCor;
    private javax.swing.JTextField idCor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableCor;
    // End of variables declaration//GEN-END:variables
}
